// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTHglCo4CFtwInyw3Louxt_u-oxuig4rM',
    appId: '1:373833368783:android:e4c71059ec1e055d3463ba',
    messagingSenderId: '373833368783',
    projectId: 'frappe-fcm-8b942',
    storageBucket: 'frappe-fcm-8b942.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuiW8V-RsxAiRdih5W7ur0UGNf-tuSUdQ',
    appId: '1:373833368783:ios:e652bb0e6f71278d3463ba',
    messagingSenderId: '373833368783',
    projectId: 'frappe-fcm-8b942',
    storageBucket: 'frappe-fcm-8b942.firebasestorage.app',
    iosBundleId: 'com.svg.smart-vision-group',
  );

}