-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgGsjcPhoNeGFUW0KT
LABSpgavL9tprbGIM4dLuB2FWpSgCgYIKoZIzj0DAQehRANCAASt/lWBe/ryPCiS
HqsFzqZAEPAMc4/WW9wHh2dwCRH8OpvKzX1nWlU95tC9RZx5wQbpVYQY56NvBTZq
GDWrlUQN
-----END PRIVATE KEY-----